# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
- package-ecosystem: devcontainers
  directories: ["/csharp", "/go", "/python"]
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: "/go"
  schedule:
    interval: weekly
- package-ecosystem: nuget
  directory: "/csharp"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: weekly
