name: "C#: Docker Image CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      context: ./csharp
      push: startsWith(github.ref, 'refs/tags/v')
      image: lpg-csharp
    permissions:
      contents: read
      packages: write
