name: "C++: Docker Image CI"

on:
  push:
    branches: [ "main" ]
    tags: ['v*']
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      context: ./cpp
      push: ${{ startsWith(github.ref, 'refs/tags/v') }}
      image: gldraphael/lpg-cpp
    permissions:
      contents: read
      packages: write
