name: "Python: Docker Image CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      context: ./python
      push: false
      image: lpg-python
    permissions:
      contents: read
      packages: write
